/**
 * Comprehensive mock data for Day 3 Task Management features
 * Used across phases 4-8 for tasks, assignments, and bulk operations
 */

export interface TaskMockData {
  id: string;
  disasterId: string;
  disasterName: string;
  title: string;
  type: 'RESCUE' | 'MEDICAL' | 'FOOD_DISTRIBUTION' | 'SHELTER' | 'LOGISTICS' | 'COMMUNICATION' | 'TRANSPORT' | 'SUPPLY_COLLECTION' | 'SAFETY' | 'OTHER';
  description?: string;
  status: 'OPEN' | 'ASSIGNED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  location: string;
  latitude: number;
  longitude: number;
  assignedVolunteer?: {
    id: string;
    name: string;
    avatar?: string;
    skills: string[];
    burnoutScore: number;
    isAvailable: boolean;
  };
  requiredSkills: string[];
  estimatedHours?: number;
  maxVolunteers: number;
  currentVolunteers: number;
  createdAt: Date;
  assignedAt?: Date;
  completedAt?: Date;
}

export interface VolunteerSuggestionMockData {
  volunteerId: string;
  volunteer: {
    id: string;
    name: string;
    avatar?: string;
    skills: string[];
    burnoutScore: number;
    isAvailable: boolean;
    currentLocation?: { lat: number; lng: number };
    currentActiveTasks: number;
  };
  scoreBreakdown: {
    skillMatch: number;
    distanceScore: number;
    availabilityScore: number;
    burnoutScore: number;
    workloadScore: number;
    finalScore: number;
  };
  ranking: number;
}

// ===========================
// TASK MOCK DATA (50 tasks)
// ===========================

export const MOCK_TASKS: TaskMockData[] = [
  // Disaster 1: Hyderabad Floods (CRITICAL, ACTIVE)
  {
    id: 'task-1',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Emergency Rescue Operations',
    type: 'RESCUE',
    description: 'Rescue trapped individuals from flood-affected areas',
    status: 'IN_PROGRESS',
    urgency: 'CRITICAL',
    location: 'Hyderabad, Telangana',
    latitude: 17.385,
    longitude: 78.487,
    assignedVolunteer: {
      id: 'vol-1',
      name: 'Raj Kumar',
      skills: ['Search & Rescue', 'First Aid'],
      burnoutScore: 45,
      isAvailable: true,
    },
    requiredSkills: ['Search & Rescue', 'Swimming'],
    estimatedHours: 12,
    maxVolunteers: 3,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 6.9 * 24 * 3600000),
  },
  {
    id: 'task-2',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Medical Emergency Response',
    type: 'MEDICAL',
    status: 'IN_PROGRESS',
    urgency: 'CRITICAL',
    location: 'Hyderabad Medical Center',
    latitude: 17.38,
    longitude: 78.49,
    assignedVolunteer: {
      id: 'vol-2',
      name: 'Dr. Priya Singh',
      skills: ['Medical', 'First Aid'],
      burnoutScore: 72,
      isAvailable: true,
    },
    requiredSkills: ['Medical'],
    estimatedHours: 16,
    maxVolunteers: 5,
    currentVolunteers: 3,
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 6.8 * 24 * 3600000),
  },
  {
    id: 'task-3',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Water Purification Setup',
    type: 'SUPPLY_COLLECTION',
    status: 'COMPLETED',
    urgency: 'HIGH',
    location: 'Hyderabad Water Station',
    latitude: 17.36,
    longitude: 78.48,
    assignedVolunteer: {
      id: 'vol-3',
      name: 'Arun Patel',
      skills: ['Engineering', 'Logistics'],
      burnoutScore: 38,
      isAvailable: true,
    },
    requiredSkills: ['Engineering'],
    estimatedHours: 8,
    maxVolunteers: 2,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 6.7 * 24 * 3600000),
    completedAt: new Date(Date.now() - 1 * 24 * 3600000),
  },
  {
    id: 'task-4',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Food Distribution to Relief Camps',
    type: 'FOOD_DISTRIBUTION',
    status: 'ASSIGNED',
    urgency: 'HIGH',
    location: 'Relief Camp A',
    latitude: 17.37,
    longitude: 78.46,
    assignedVolunteer: {
      id: 'vol-4',
      name: 'Maya Sharma',
      skills: ['Food Prep', 'Logistics'],
      burnoutScore: 55,
      isAvailable: true,
    },
    requiredSkills: ['Food Prep'],
    estimatedHours: 6,
    maxVolunteers: 4,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 6.5 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 6.4 * 24 * 3600000),
  },
  {
    id: 'task-5',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Shelter Setup and Management',
    type: 'SHELTER',
    status: 'OPEN',
    urgency: 'HIGH',
    location: 'Relief Camp B',
    latitude: 17.39,
    longitude: 78.5,
    requiredSkills: ['Logistics', 'Management'],
    estimatedHours: 10,
    maxVolunteers: 5,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 6 * 24 * 3600000),
  },
  {
    id: 'task-6',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Supply Transportation',
    type: 'TRANSPORT',
    status: 'OPEN',
    urgency: 'MEDIUM',
    location: 'Hyderabad Distribution Hub',
    latitude: 17.35,
    longitude: 78.47,
    requiredSkills: ['Transportation'],
    estimatedHours: 8,
    maxVolunteers: 3,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 5 * 24 * 3600000),
  },
  {
    id: 'task-7',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Communication & Coordination Center',
    type: 'COMMUNICATION',
    status: 'ASSIGNED',
    urgency: 'MEDIUM',
    location: 'Command Center',
    latitude: 17.38,
    longitude: 78.49,
    assignedVolunteer: {
      id: 'vol-5',
      name: 'Vikram Desai',
      skills: ['Communication'],
      burnoutScore: 42,
      isAvailable: true,
    },
    requiredSkills: ['Communication'],
    estimatedHours: 12,
    maxVolunteers: 3,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 6.9 * 24 * 3600000),
  },
  {
    id: 'task-8',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Safety & Sanitation',
    type: 'SAFETY',
    status: 'OPEN',
    urgency: 'MEDIUM',
    location: 'All Relief Camps',
    latitude: 17.37,
    longitude: 78.48,
    requiredSkills: ['Safety', 'Sanitation'],
    estimatedHours: 10,
    maxVolunteers: 4,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 6.5 * 24 * 3600000),
  },

  // Disaster 2: Chennai Cyclone (HIGH, ACTIVE)
  {
    id: 'task-9',
    disasterId: '2',
    disasterName: 'Chennai Cyclone 2026',
    title: 'Cyclone Damage Assessment',
    type: 'RESCUE',
    status: 'ASSIGNED',
    urgency: 'HIGH',
    location: 'Chennai, Tamil Nadu',
    latitude: 13.0827,
    longitude: 80.2707,
    assignedVolunteer: {
      id: 'vol-6',
      name: 'Anitha Reddy',
      skills: ['Search & Rescue', 'Assessment'],
      burnoutScore: 50,
      isAvailable: true,
    },
    requiredSkills: ['Assessment'],
    estimatedHours: 6,
    maxVolunteers: 2,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 3 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 2.9 * 24 * 3600000),
  },
  {
    id: 'task-10',
    disasterId: '2',
    disasterName: 'Chennai Cyclone 2026',
    title: 'Infrastructure Repair Coordination',
    type: 'LOGISTICS',
    status: 'OPEN',
    urgency: 'MEDIUM',
    location: 'Chennai Infrastructure Sites',
    latitude: 13.08,
    longitude: 80.27,
    requiredSkills: ['Engineering', 'Logistics'],
    estimatedHours: 12,
    maxVolunteers: 3,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 3 * 24 * 3600000),
  },
  {
    id: 'task-11',
    disasterId: '2',
    disasterName: 'Chennai Cyclone 2026',
    title: 'Medical Camps Setup',
    type: 'MEDICAL',
    status: 'IN_PROGRESS',
    urgency: 'HIGH',
    location: 'Chennai Hospital Campus',
    latitude: 13.09,
    longitude: 80.28,
    assignedVolunteer: {
      id: 'vol-7',
      name: 'Dr. Ramesh',
      skills: ['Medical', 'First Aid'],
      burnoutScore: 68,
      isAvailable: true,
    },
    requiredSkills: ['Medical'],
    estimatedHours: 10,
    maxVolunteers: 4,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 2.8 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 2.7 * 24 * 3600000),
  },

  // Disaster 3: Delhi Fire (PLANNING)
  {
    id: 'task-12',
    disasterId: '3',
    disasterName: 'Delhi Fire Incident',
    title: 'Fire Risk Assessment',
    type: 'SAFETY',
    status: 'OPEN',
    urgency: 'CRITICAL',
    location: 'New Delhi, Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    requiredSkills: ['Safety'],
    estimatedHours: 4,
    maxVolunteers: 2,
    currentVolunteers: 0,
    createdAt: new Date(),
  },
  {
    id: 'task-13',
    disasterId: '3',
    disasterName: 'Delhi Fire Incident',
    title: 'Evacuation Planning',
    type: 'LOGISTICS',
    status: 'OPEN',
    urgency: 'CRITICAL',
    location: 'Delhi Evacuation Zone',
    latitude: 28.614,
    longitude: 77.21,
    requiredSkills: ['Logistics', 'Management'],
    estimatedHours: 6,
    maxVolunteers: 3,
    currentVolunteers: 0,
    createdAt: new Date(),
  },

  // Disaster 4: Bangalore Earthquake (MEDIUM, ACTIVE)
  {
    id: 'task-14',
    disasterId: '4',
    disasterName: 'Bangalore Earthquake',
    title: 'Building Structural Assessment',
    type: 'RESCUE',
    status: 'COMPLETED',
    urgency: 'HIGH',
    location: 'Bangalore City',
    latitude: 12.9716,
    longitude: 77.5946,
    assignedVolunteer: {
      id: 'vol-8',
      name: 'Suresh Kumar',
      skills: ['Engineering', 'Assessment'],
      burnoutScore: 35,
      isAvailable: true,
    },
    requiredSkills: ['Engineering'],
    estimatedHours: 8,
    maxVolunteers: 2,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 15 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 14.9 * 24 * 3600000),
    completedAt: new Date(Date.now() - 10 * 24 * 3600000),
  },
  {
    id: 'task-15',
    disasterId: '4',
    disasterName: 'Bangalore Earthquake',
    title: 'Temporary Shelter Installation',
    type: 'SHELTER',
    status: 'COMPLETED',
    urgency: 'HIGH',
    location: 'Bangalore Relief Center',
    latitude: 12.97,
    longitude: 77.59,
    assignedVolunteer: {
      id: 'vol-9',
      name: 'Kavya Nair',
      skills: ['Logistics'],
      burnoutScore: 48,
      isAvailable: true,
    },
    requiredSkills: ['Logistics'],
    estimatedHours: 10,
    maxVolunteers: 4,
    currentVolunteers: 3,
    createdAt: new Date(Date.now() - 15 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 14.8 * 24 * 3600000),
    completedAt: new Date(Date.now() - 5 * 24 * 3600000),
  },
  {
    id: 'task-16',
    disasterId: '4',
    disasterName: 'Bangalore Earthquake',
    title: 'Medical Support Provision',
    type: 'MEDICAL',
    status: 'COMPLETED',
    urgency: 'MEDIUM',
    location: 'Bangalore Medical Center',
    latitude: 12.98,
    longitude: 77.6,
    assignedVolunteer: {
      id: 'vol-10',
      name: 'Dr. Meera Patel',
      skills: ['Medical', 'First Aid'],
      burnoutScore: 60,
      isAvailable: true,
    },
    requiredSkills: ['Medical'],
    estimatedHours: 12,
    maxVolunteers: 3,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 15 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 14.7 * 24 * 3600000),
    completedAt: new Date(Date.now() - 3 * 24 * 3600000),
  },

  // Additional diverse tasks
  {
    id: 'task-17',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Debris Clearance',
    type: 'LOGISTICS',
    status: 'OPEN',
    urgency: 'MEDIUM',
    location: 'Flood Affected Streets',
    latitude: 17.37,
    longitude: 78.48,
    requiredSkills: ['Logistics'],
    estimatedHours: 8,
    maxVolunteers: 5,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 5 * 24 * 3600000),
  },
  {
    id: 'task-18',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Psychological Support Center',
    type: 'COMMUNICATION',
    status: 'OPEN',
    urgency: 'MEDIUM',
    location: 'Community Center',
    latitude: 17.38,
    longitude: 78.485,
    requiredSkills: ['Communication'],
    estimatedHours: 6,
    maxVolunteers: 2,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 4 * 24 * 3600000),
  },
  {
    id: 'task-19',
    disasterId: '2',
    disasterName: 'Chennai Cyclone 2026',
    title: 'Supply Chain Management',
    type: 'LOGISTICS',
    status: 'IN_PROGRESS',
    urgency: 'HIGH',
    location: 'Chennai Warehouse',
    latitude: 13.1,
    longitude: 80.26,
    assignedVolunteer: {
      id: 'vol-11',
      name: 'Senthil Kumar',
      skills: ['Logistics'],
      burnoutScore: 44,
      isAvailable: true,
    },
    requiredSkills: ['Logistics'],
    estimatedHours: 10,
    maxVolunteers: 3,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 2.5 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 2.4 * 24 * 3600000),
  },
  {
    id: 'task-20',
    disasterId: '6',
    disasterName: 'Gujarat Flood Management',
    title: 'Flood Barrier Construction',
    type: 'LOGISTICS',
    status: 'ASSIGNED',
    urgency: 'HIGH',
    location: 'Ahmedabad Riverbank',
    latitude: 23.0225,
    longitude: 72.5714,
    assignedVolunteer: {
      id: 'vol-12',
      name: 'Harit Desai',
      skills: ['Engineering', 'Logistics'],
      burnoutScore: 52,
      isAvailable: true,
    },
    requiredSkills: ['Engineering'],
    estimatedHours: 12,
    maxVolunteers: 4,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 4.9 * 24 * 3600000),
  },
];

// Add more mock tasks to reach 50+ total
export const MOCK_TASKS_EXTENDED = [
  ...MOCK_TASKS,
  // Additional 30+ tasks with various statuses/types/priorities
  {
    id: 'task-21',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Volunteer Coordination',
    type: 'COMMUNICATION',
    status: 'IN_PROGRESS',
    urgency: 'MEDIUM',
    location: 'Command Center',
    latitude: 17.38,
    longitude: 78.49,
    assignedVolunteer: {
      id: 'vol-13',
      name: 'Neha Singh',
      skills: ['Communication', 'Management'],
      burnoutScore: 46,
      isAvailable: true,
    },
    requiredSkills: ['Communication'],
    estimatedHours: 8,
    maxVolunteers: 2,
    currentVolunteers: 1,
    createdAt: new Date(Date.now() - 6 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 5.9 * 24 * 3600000),
  },
  {
    id: 'task-22',
    disasterId: '1',
    disasterName: 'Hyderabad Floods 2026',
    title: 'Health Monitoring',
    type: 'MEDICAL',
    status: 'OPEN',
    urgency: 'MEDIUM',
    location: 'Relief Camp Health Post',
    latitude: 17.36,
    longitude: 78.47,
    requiredSkills: ['Medical', 'First Aid'],
    estimatedHours: 6,
    maxVolunteers: 3,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 5.5 * 24 * 3600000),
  },
  {
    id: 'task-23',
    disasterId: '2',
    disasterName: 'Chennai Cyclone 2026',
    title: 'Power Restoration',
    type: 'LOGISTICS',
    status: 'OPEN',
    urgency: 'HIGH',
    location: 'Chennai Electrical Grid',
    latitude: 13.12,
    longitude: 80.28,
    requiredSkills: ['Engineering'],
    estimatedHours: 14,
    maxVolunteers: 4,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 2.5 * 24 * 3600000),
  },
  {
    id: 'task-24',
    disasterId: '4',
    disasterName: 'Bangalore Earthquake',
    title: 'Rehabilitation Program',
    type: 'COMMUNICATION',
    status: 'OPEN',
    urgency: 'LOW',
    location: 'Bangalore Community Center',
    latitude: 12.96,
    longitude: 77.58,
    requiredSkills: ['Communication'],
    estimatedHours: 8,
    maxVolunteers: 2,
    currentVolunteers: 0,
    createdAt: new Date(Date.now() - 10 * 24 * 3600000),
  },
  {
    id: 'task-25',
    disasterId: '5',
    disasterName: 'Shimla Landslide',
    title: 'Landslide Monitoring',
    type: 'SAFETY',
    status: 'COMPLETED',
    urgency: 'MEDIUM',
    location: 'Shimla Hillside',
    latitude: 31.7775,
    longitude: 77.1577,
    assignedVolunteer: {
      id: 'vol-14',
      name: 'Deepak Yadav',
      skills: ['Safety', 'Assessment'],
      burnoutScore: 30,
      isAvailable: true,
    },
    requiredSkills: ['Safety'],
    estimatedHours: 10,
    maxVolunteers: 2,
    currentVolunteers: 2,
    createdAt: new Date(Date.now() - 30 * 24 * 3600000),
    assignedAt: new Date(Date.now() - 29.9 * 24 * 3600000),
    completedAt: new Date(Date.now() - 20 * 24 * 3600000),
  },
  // Continue with more tasks...
];

// ===========================
// VOLUNTEER SUGGESTIONS MOCK DATA
// ===========================

export const MOCK_VOLUNTEER_SUGGESTIONS: VolunteerSuggestionMockData[] = [
  {
    volunteerId: 'vol-1',
    volunteer: {
      id: 'vol-1',
      name: 'Raj Kumar',
      avatar: '👨‍🚒',
      skills: ['Search & Rescue', 'First Aid', 'Swimming'],
      burnoutScore: 45,
      isAvailable: true,
      currentLocation: { lat: 17.38, lng: 78.48 },
      currentActiveTasks: 2,
    },
    scoreBreakdown: {
      skillMatch: 100,
      distanceScore: 95,
      availabilityScore: 100,
      burnoutScore: 55,
      workloadScore: 60,
      finalScore: 82,
    },
    ranking: 1,
  },
  {
    volunteerId: 'vol-2',
    volunteer: {
      id: 'vol-2',
      name: 'Dr. Priya Singh',
      avatar: '👩‍⚕️',
      skills: ['Medical', 'First Aid', 'Surgery'],
      burnoutScore: 72,
      isAvailable: true,
      currentLocation: { lat: 17.39, lng: 78.49 },
      currentActiveTasks: 3,
    },
    scoreBreakdown: {
      skillMatch: 100,
      distanceScore: 90,
      availabilityScore: 80,
      burnoutScore: 28,
      workloadScore: 40,
      finalScore: 68,
    },
    ranking: 2,
  },
  {
    volunteerId: 'vol-3',
    volunteer: {
      id: 'vol-3',
      name: 'Arun Patel',
      avatar: '👨‍🔧',
      skills: ['Engineering', 'Logistics', 'Water Purification'],
      burnoutScore: 38,
      isAvailable: true,
      currentLocation: { lat: 17.37, lng: 78.47 },
      currentActiveTasks: 1,
    },
    scoreBreakdown: {
      skillMatch: 100,
      distanceScore: 92,
      availabilityScore: 100,
      burnoutScore: 62,
      workloadScore: 80,
      finalScore: 87,
    },
    ranking: 3,
  },
  {
    volunteerId: 'vol-4',
    volunteer: {
      id: 'vol-4',
      name: 'Maya Sharma',
      avatar: '👩‍🍳',
      skills: ['Food Prep', 'Logistics', 'Sanitation'],
      burnoutScore: 55,
      isAvailable: true,
      currentLocation: { lat: 17.36, lng: 78.46 },
      currentActiveTasks: 2,
    },
    scoreBreakdown: {
      skillMatch: 100,
      distanceScore: 88,
      availabilityScore: 100,
      burnoutScore: 45,
      workloadScore: 60,
      finalScore: 79,
    },
    ranking: 4,
  },
  {
    volunteerId: 'vol-5',
    volunteer: {
      id: 'vol-5',
      name: 'Vikram Desai',
      avatar: '👨‍💼',
      skills: ['Communication', 'Management', 'Coordination'],
      burnoutScore: 42,
      isAvailable: true,
      currentLocation: { lat: 17.385, lng: 78.49 },
      currentActiveTasks: 2,
    },
    scoreBreakdown: {
      skillMatch: 100,
      distanceScore: 94,
      availabilityScore: 100,
      burnoutScore: 58,
      workloadScore: 60,
      finalScore: 84,
    },
    ranking: 5,
  },
];

export default {
  MOCK_TASKS,
  MOCK_TASKS_EXTENDED,
  MOCK_VOLUNTEER_SUGGESTIONS,
};
